name = "EpicCobblemon"
author = "Bwc9876"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be66952d146baad0ee3a33b06037a0acb60d06c2a63e1f79f3cfec278940ebce"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
