name = "EpicCobblemon"
author = "Bwc9876"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37ca4e84f818995397cbcaf0f6611d51686c91bfe6bd63057e55d18c30319e59"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
