name = "EpicCobblemon"
author = "Bwc9876"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e09a820d9f8a95b5aef9b73790ed99d95f1799ede3808b1f4de4d6582b5f53a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
